# Generated by Django 5.2.3 on 2025-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User'), ('ADMIN', 'Admin'), ('HR', 'HR Recruiter')], default='HR', max_length=20),
        ),
    ]
