# Generated by Django
from django.db import migrations

def update_hr_to_recruiter(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Update all users with role "HR" to "RECRUITER"
    User.objects.filter(role="HR").update(role="RECRUITER")

def revert_recruiter_to_hr(apps, schema_editor):
    User = apps.get_model("users", "User")
    # Revert "RECRUITER" to "HR"
    User.objects.filter(role="RECRUITER").update(role="HR")

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_company"),
    ]

    operations = [
        migrations.RunPython(update_hr_to_recruiter, revert_recruiter_to_hr),
    ]
