# Generated by Django 5.2.3 on 2026-02-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_update_hr_role_to_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate'), ('SUPERUSER', 'Superuser')], default='RECRUITER', max_length=20),
        ),
    ]
