# Generated by Django 5.2.3 on 2026-02-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'SuperUser'), ('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default='RECRUITER', max_length=20),
        ),
    ]
