# Generated by Django 5.2.8 on 2025-11-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
