# Generated by Django 5.2.3 on 2026-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'SuperUser'), ('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter')], default='RECRUITER', max_length=20),
        ),
    ]
