# Generated by Django 5.2.3 on 2026-02-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_candidate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter')], default='RECRUITER', max_length=20),
        ),
    ]
