# Generated by Django 5.2.8 on 2025-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_invite_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created_by_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
