# Generated by Django 5.2.3 on 2026-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_created_at_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('RECRUITER', 'Recruiter')], max_length=20, null=True),
        ),
    ]
