# Generated by Django 5.2.3 on 2025-12-11 09:19

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to=applications.models.resume_upload_path)),
                ('parsed_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parsed_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('parsed_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parsed_skills', models.JSONField(blank=True, null=True)),
                ('parsed_experience', models.FloatField(blank=True, null=True)),
                ('parsed_projects', models.TextField(blank=True, null=True)),
                ('parsed_education', models.TextField(blank=True, null=True)),
                ('parsed_certifications', models.TextField(blank=True, null=True)),
                ('parsed_keywords', models.JSONField(blank=True, null=True)),
                ('match_score', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('experience_score', models.FloatField(default=0)),
                ('skill_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('summary', models.TextField(blank=True, null=True)),
                ('evaluation', models.TextField(blank=True, null=True)),
                ('fit_category', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('screening', 'Screening'), ('review', 'Review'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='screening', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
