# Generated by Django 5.2.3 on 2025-12-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='migration_fix',
            field=models.BooleanField(default=False),
        ),
    ]
