# Generated by Django 5.2.8 on 2025-12-01 11:54

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=applications.models.resume_upload_path),
        ),
    ]
