# Generated by Django 5.2.8 on 2025-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_created_at_application_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
