# Generated by Django 5.2.3 on 2025-12-30 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_migration_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='migration_fix',
        ),
    ]
