# Generated by Django 5.2.3 on 2025-12-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_resume'),
        ('jobs', '0007_job_required_education'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'email')},
        ),
    ]
