# Generated by Django 5.2.8 on 2025-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_experience_years_application_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='parsed_text',
            new_name='parsed_certifications',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='experience_years',
            new_name='parsed_experience',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='keywords',
            new_name='parsed_keywords',
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='parsed_projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
