# Generated by Django 5.2.3 on 2026-03-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_migration_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='parsed_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='parsed_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='parsed_phone',
        ),
    ]
