# Generated by Django 5.2.8 on 2025-12-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_parsed_text_application_parsed_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='keyword_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='skill_score',
            field=models.FloatField(default=0),
        ),
    ]
