# Generated by Django 5.2.3 on 2025-12-24 13:13

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=applications.models.resume_upload_path),
        ),
    ]
