# Generated by Django 5.2.3 on 2025-12-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='parsed_keywords',
        ),
    ]
