# Generated by Django 5.2.8 on 2025-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_deadline_job_employment_type_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(default=list),
        ),
    ]
