# Generated by Django 5.2.3 on 2025-12-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('yearly', 'Yearly (LPA)'), ('monthly', 'Monthly (INR)'), ('negotiable', 'Negotiable'), ('not_disclosed', 'Not Disclosed')], default='yearly', max_length=20),
        ),
    ]
