# Generated by Django 5.2.8 on 2025-12-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='openings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
