# Generated by Django 5.2.3 on 2025-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
