# Generated by Django 5.2.8 on 2025-12-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_openings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='openings',
            new_name='Vacancies',
        ),
    ]
