# Generated by Django 5.2.3 on 2025-12-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_max_salary_alter_job_min_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
