# Generated by Django 5.2.3 on 2025-12-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_max_salary_alter_job_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_education',
            field=models.CharField(blank=True, help_text='Example: B.Tech CS, MCA, Any Graduate', max_length=255, null=True),
        ),
    ]
