# Generated by Django 5.2.8 on 2025-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
