# Generated by Django 5.2.8 on 2025-12-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_jd_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
